apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ses-bounce-data
  namespace: ses-bounce
  labels:
    app.kubernetes.io/name: ses-bounce-webhook
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
